# Generated by Django 5.2.10 on 2026-02-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurFeaturedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=20)),
                ('date', models.DateField()),
                ('title', models.CharField()),
                ('image', models.ImageField(upload_to='OurFeaturedPost')),
            ],
        ),
    ]
