# Generated by Django 5.2.10 on 2026-02-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourfeaturedpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
