# Generated by Django 5.2.10 on 2026-02-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ourfeaturedpost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourfeaturedpost',
            name='descriptions',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourfeaturedpost',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ourfeaturedpost',
            name='title',
            field=models.TextField(),
        ),
    ]
