# Generated by Django 5.2.10 on 2026-02-12 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ourfeaturedpost_descriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('descriptions', models.TextField()),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(upload_to='CategoriesAbout')),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_about', to='blog.category')),
            ],
        ),
    ]
